import { IDocOptions } from './interfaces/doc-options.interface';

export const apiTitle = 'Web3 Token Information Service';
export const apiDescription =
  'This service allows users to fetch token information based on their access keys. It respects the rate limits and expiration times defined in the keys generated by Acess key service';

export const adminTags = ['Token'];

export const token: IDocOptions = {
  tagGroupName: 'Token',
  tags: adminTags,
};

export const xTagGroups = [
  {
    name: token.tagGroupName,
    tags: token.tags,
  },
];
